### ISSUE TITLE
[Regression] Input not passed to game when recording with Unity Recorder

### ISSUE THREAD

**Issue by JohannesDeml** [Unity-Technologies/InputSystem#1070] opened 2020-02-19 15:49 UTC
# Description
When running a recording with [Unity Recorder](https://docs.unity3d.com/Packages/com.unity.recorder@2.1/manual/index.html) no input gets passed to the game. This is a regression bug since preview 4.

## System
* Unity 2019.3.1f1
* Unity Recorder preview.1 - 2.1.0
* Input: Mouse/Keyboard

### Affected Versions
* preview.4 - 1.0.0
* preview.5 - 1.0.0

### Not Affected
* preview.3 - 1.0.0

### Settings
![grafik](https://user-images.githubusercontent.com/4518980/74848989-81d95780-5338-11ea-93cd-da9b32dad102.png)
  m_UpdateMode: 1
  m_CompensateForScreenOrientation: 1
  m_FilterNoiseOnCurrent: 0
  m_DefaultDeadzoneMin: 0.125
  m_DefaultDeadzoneMax: 0.925
  m_DefaultButtonPressPoint: 0.5
  m_DefaultTapTime: 0.2
  m_DefaultSlowTapTime: 0.5
  m_DefaultHoldTime: 0.4
  m_TapRadius: 5
  m_MultiTapDelayTime: 0.75

**Comment by stefanunity** [comment] 2020-02-20 12:50
I tried this myself using the versions you mentioned but can't reproduce this :(
Could you be so nice to submit a bug report through the editor with a repro project?
Thanks!

**Comment by JohannesDeml** [comment] 2020-02-20 14:14
Okay got it, I'll try to do a repro once I got the time. Sorry for wasting your time, I was pretty sure that it was a general bug, since switching versions back and forth created the problem and got rid of it, and only happens while recording.

**Comment by JohannesDeml** [comment] 2020-02-21 09:44
Hi again @stefanunity,

so I found the time to do a very simple repro, so I'm quite confident that it is an actual bug.
https://github.com/JohannesDeml/InputSystemRecorderBug

Should I do a bug reprot through the editor as well, or is this issue enough for you?

Some new things I found:
* The bug does not happen when the play mode is started through the recorder
* The bug persists after recording has finished for that play session

**Comment by stefanunity** [comment] 2020-02-21 12:10
Your project and the extra info are good! I got a repro myself here with it and will pass it on to the devs. We're going to track it further at https://issuetracker.unity3d.com/product/unity/issues/guid/1221768/ and I'll be closing this github issue.

Thanks again for your efforts!

**Closed as completed by stefanunity** 2020-02-21 12:10 UTC

**Comment by JohannesDeml** [comment] 2020-02-21 14:32
Cool, thanks for the quick check and confirmation, I'm happy I was able to help :)
