### ISSUE TITLE
Gamepad Input is not processed when Game View is not focused

### ISSUE THREAD

**Issue by douglas-piconi** [Unity-Technologies/InputSystem#430] opened 2019-02-21 15:42 UTC
How to reproduce:

1. Open attached project
2. Open scene InputTest.unity
 - Make sure you have a controller attached
3. Play the scene
4. Wiggle the left joystick of the controller
 - Note it prints the x and y axes
5. Click Clear in the console
 - This defocuses the game view and focuses on the console window instead
6. Wiggle the left joystick again
 - Note how nothing is printed in the console now

 - This does not happen on OSX; the controller is always detected there

**Comment by douglas-piconi** [comment] 2019-02-21 15:44
This is related to bug https://github.com/Unity-Technologies/InputSystem/issues/376

parts of this are both bug and enhancement, and will need to be coordinated with controlling the UI with the Stick.

**Comment by JiaUnity** [comment] 2019-03-20 00:56
This should be by design.

**Comment by JiaUnity** [comment] 2019-04-19 22:53
I notice when I test with both input systems enabled, the old one never shows input when Game view is out of focus during Play mode. I think the new one should be the same.
I also think it is a reasonable design. If a customer wants to make adjustment in the Scene, having input pass into the Game may interrupt the view. 
I'm closing this as By Design. If there is any corner case should be exempted, I suggest we evaluate those separately.

**Closed as completed by JiaUnity** 2019-04-19 22:53 UTC
Labels: bug, enhancement
