### ISSUE TITLE
XInput motor values are incorrect

### ISSUE THREAD

**Issue by caosdoar** [Unity-Technologies/InputSystem#420] opened 2019-02-18 10:34 UTC
The values given to SetMotorSpeeds() to a xbox 360 controller (XInput Gamepad) are not translated correctly to the USB data given to the device. Meaning that a value of 0.1f can put the motors to full speed while 0.2f is barely moving.

The behaviour can be tested with an xbox 360 controller attached and the following code:

```
using UnityEngine;
using UnityEngine.Experimental.Input;

public class MyGamepad : MonoBehaviour
{
    void Update()
    {
        var gamepad = Gamepad.current;
        if (gamepad != null)
        {
            gamepad.SetMotorSpeeds(gamepad.leftTrigger.ReadValue(), gamepad.rightTrigger.ReadValue());
        }
    }
}
```

Slowly increasing the pressure on one of the gamepad triggers should slowly increase the motors speed but instead it wildly fluctuates between no speed and full speed.

It looks like the "RMBL" command sent by IOCTL is not expecting float values (maybe).  I tried debugging the USB data transfered but couldn't figure out what conversion is done. I bruteforced some thousand values and I got a hack solution for the RMBL command:

```
public void SetMotors(float lowFreq, float hiFreq)
{
    // byte3 at 0x38 means an output of 0x80
    // with byte3 at that value byte1 substracts from that
    byte3 = 0x38;
    byte0 = (byte)(384 - Mathf.Clamp01(lowFreq) * 255);
    byte7 = 0x38;
    byte4 = (byte)(384 - Mathf.Clamp01(hiFreq) * 255);
}
```

Where byte0 to byte7 are the 8 bytes for the RMBL command.

I'm trying to get a DualShock3 controller to support rumble as well through HID but the HIDO command seems to be transforming my data in some way as well. Is there any way I can get some information on how the HIDO command works internally? :)

**Comment by Rene-Damm** [comment] 2019-02-19 15:01
Confirmed. Backend does this

```
                    vibration.wLeftMotorSpeed = 65535 / rumble->lowFrequencyMotorSpeed;
                    vibration.wRightMotorSpeed = 65535 / rumble->highFrequencyMotorSpeed;
```

when it should be doing this

```
                    vibration.wLeftMotorSpeed = 65535 * rumble->lowFrequencyMotorSpeed;
                    vibration.wRightMotorSpeed = 65535 * rumble->highFrequencyMotorSpeed;
```

>Is there any way I can get some information on how the HIDO command works internally? :)

HID output reports are sent to the device as is. I.e. `DualShockHIDOutputReport` is sent as a binary blob to the device. `DualShockHIDOutputReport.SetMotorSpeeds` performs the translation.

**Comment by caosdoar** [comment] 2019-02-19 15:07
Thank you for the response Rene!
I scratched my head for a while with that.

Good to know that about the HID output report. I guess what I'm looking at is the data transformed by the driver or something. I will give another try to reverse engineering the output report of the DualShock3.

Cheers

**Comment by Rene-Damm** [comment] 2019-02-19 15:17
>I will give another try to reverse engineering the output report of the DualShock3.

Oh, I missed one little detail there. You said DualShock 3. ATM the code only supports the DualShock 4 controller. Support for the DS3 controller is on the TODO list.

For the HID output report format of the DS3, there's several sites around the internet that have docs and/or code snippets for the controller. The DS3 formats in general are much better understood. Even the sensor formats seem to mostly be well understood.

**Comment by caosdoar** [comment] 2019-02-19 16:03
I was doing my own implementation of the DS3 and I tried to follow different implementations, including the sixaxis driver for linux. But nothing seems to match with the windows drivers installed by the "Playstation Now" software. 

To be fair I'm not using "InputSystem" but a very simple implementation of my own to support rumble and gamepad-to-player asignment for a game, and I wanted to support DS3 as seems to be a significant amount of people using it with steam.

I figured out the bytes that controls the on/off/blink state of the 4 leds and some bytes involved in the speed of the blinking but thats all. And those bytes does not match any description I found anywhere. 

But I wouldn't like to distract you from your work. Thank you for your help again!

**Comment by douglas-piconi** [comment] 2019-03-01 21:02
Bug found in the Unity Editor code.  Fix will go into 2019.2 alpha, 2019.1 beta, and hopefully 2018.3 patch release.   I will update the ticket when the fix lands in each public release.   Unfortunately @caosdoar the Unity Editor fixes take weeks to land instead of an instant fix in the input package.  I'll keep you updated

**Comment by caosdoar** [comment] 2019-03-01 22:22
Thank you for the update Douglas.

**Comment by douglas-piconi** [comment] 2019-03-11 19:17
@caosdoar Exact release of fix will be in Unity 2019.2.0a9 and 2019.1.0b8

**Closed as completed by douglas-piconi** 2019-03-11 19:17 UTC
Labels: bug

**Comment by caosdoar** [comment] 2019-03-11 19:52
@douglas-piconi Is 2018.3 not getting a fix for this?

**Comment by douglas-piconi** [comment] 2019-03-11 19:58
@caosdoar Right now 2018.3 is being certified for the LTS (long term support) release of unity.  Release management is only taking the most serious and critical unity bug fixes for that release.  Due to the fact that the new input system is in preview/beta, its not being considered a critical feature for 2018.3. This fix even though its small and not risky, has not been approved to get back-ported to the 2018.3 branch.  Its sitting there "waiting" to go into 2018.3 but hasn't made it.

**Comment by caosdoar** [comment] 2019-03-11 20:01
Thank you for the information @douglas-piconi
