### ISSUE TITLE
XInputController sticks work correctly only when game is out of focus

### ISSUE THREAD

**Issue by althaj** [Unity-Technologies/InputSystem#398] opened 2019-01-29 22:38 UTC
When I click out of the game window (for example into hierarchy or even outside of Unity), the sticks work properly. However, when the game window is focused the sticks randomly "freeze", they are stuck on the same value even when I move them or keep them centered.

I use Logitech F310.

**Comment by douglas-piconi** [comment] 2019-02-14 16:04
I can repro the problem, but with the opposite behavior.   when I click outside of the game window, the values are not updating.  In the input debugger I can see the stick values, but in the game screen they are frozen just like you described.   Not quite sure if this is a problem with the UI or the the way the new input system interacts with the UI.   I will investigate.

**Comment by douglas-piconi** [comment] 2019-02-14 16:31
actually, if I download the space shooter tutorial with the old input manager.  I get the same behavior.  This may be as intended.

**Comment by althaj** [comment] 2019-02-17 06:10
I'm starting to think this was issue with new version of Unity (that is not even supported by this experimental input). With the 2018.3 version I don't get this behavior anymore.

**Comment by douglas-piconi** [comment] 2019-02-19 15:19
I'm going to go ahead and close this for now.

**Closed as completed by douglas-piconi** 2019-02-19 15:19 UTC
