### ISSUE TITLE
Button PressAndRelease now has incorrect/unstable behaviors in 0.2.6 preview

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#493] opened 2019-03-24 21:06 UTC
[PressButtonGamepadMinRepro.zip](https://github.com/Unity-Technologies/InputSystem/files/3000846/PressButtonGamepadMinRepro.zip)

In this sample, buttonSouth/keyboard s produces Performed on both press and release when the Continious flag is set to false. I'm no longer seeing Canceled like the previous package versions.

If I set the Continous flag to true, Performed is spammed infinitely and doesn't stop when the button is released.

Win10 64, keyboard, PS4 DualShock, XBOX One Gamepad.

**Comment by JiaUnity** [comment] 2019-03-27 00:50
This is by design. 
@Rene-Damm can you confirm?

**Comment by WaynGames** [comment] 2019-04-19 17:20
Hello, if it is by design, I think it should also triger when another key is pressed. 
For mouvement wqsd if I press "d" I i get a Vector2 (1,0) 
If I release I get a (0,0), 
so far so good.
But I can never get a (0.7,0.7) I always presse one key first and the the other one does not trigger anything.
If it's the "Pass Through" intended purpose, it does not work.

**Comment by periodyctom** [comment] 2019-04-30 19:42
The problem I experienced is I'm getting 2 "Performed" events, there is no way to tell when the action begins or ends. If it produced Started -> Performed or Performed -> Canceled then I can disambiguate.

**Comment by Rallix** [comment] 2019-05-22 20:25
Exactly – "Press and Release" used to send different events during the _Press_ and _Release_ stage. Now it doesn't; so unless you keep track of the 'pressed' status of your buttons by yourself, you can't tell the stages apart.

**Comment by JiaUnity** [comment] 2019-05-22 23:50
This is fixed in the latest package release 0.3.0-preview. Closing

@periodyctom @tomas-jezek if you want to differentiate the press and release, "Press" interactions is not the right choice. I suggest using Tap or Slow Tap, which generates both Started and Performed.

**Closed as completed by JiaUnity** 2019-05-22 23:50 UTC
