### ISSUE TITLE
[Windows] touchscreen.current.activeTouches does not correctly report multiple touches

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#89] opened 2018-04-26 21:14 UTC
[ActiveTouchTest.zip](https://github.com/Unity-Technologies/InputSystem/files/1953000/ActiveTouchTest.zip)

Reproduce using the scene in the attached project.  The UI will indicate when a touch is active and its reported screen position.
(1) Multitouch does not seem to work
(2) By tapping 2 separate fingers in quick succession, you can get a additional touches to appear, but the originial touches become "dead."  Dead touches do not update their position and are not removed from the activeTouch list.

Found in commit b03c6f23b74b76596966a634a67ff74f354f8e17 with editor commit 725fd26e2382 on a Razer laptop with touchscreen.

**Comment by Rene-Damm** [comment] 2018-04-30 17:38
I see touch behaving properly outside of play mode so my thinking is that this is a bug in the state maintenance code itself. I.e. rather than `Touchscreen` doing something wrong, it's probably `InputManager`'s handling of `IStateCallbackReceiver` where things blow up.

**Comment by todi1856** [comment] 2018-05-02 19:31
The issue reproduces in Editor as well

**Comment by todi1856** [comment] 2018-05-08 11:50
Test showing the issue.
`   
public void Devices_TouchscreenPhasesResets()
    {
        var device = InputSystem.AddDevice<Touchscreen>();

        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Began,
               touchId = 92,
           });
        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Moved,
               touchId = 92,
           });

        InputSystem.Update();

        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Ended,
               touchId = 92,
           });
        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Began,
               touchId = 93,
           });
        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Moved,
               touchId = 93,
           });

        InputSystem.Update();

        InputSystem.QueueStateEvent(device,
           new TouchState
           {
               phase = PointerPhase.Ended,
               touchId = 93,
           });


        InputSystem.Update();
        InputSystem.Update();

        Assert.That(device.allTouchControls[0].phase.ReadValue(), Is.EqualTo(PointerPhase.None));
        Assert.That(device.allTouchControls[1].phase.ReadValue(), Is.EqualTo(PointerPhase.None));
        Assert.That(device.activeTouches.Count, Is.Zero);

    }`

Seems the issue is with OnCarryStateForward, waiting for @Rene-Damm to try out the test.

**Comment by Rene-Damm** [comment] 2018-05-15 00:50
Hey @jackpr-unity, could you give the fix above a spin and see if this resolves the issue for you?

**Comment by jackpr-unity** [comment] 2018-05-16 19:34
Multiple touches now register, but I still get ghost touches.

2018.2.0b4, changeset 08c87fc4c6268bcc2d9644f828d98fc6736e4e85

**Comment by todi1856** [comment] 2018-06-14 13:05
Found a test which reproduces this:
`
    [Test]
    [Category("Devices")]
    public void Devices_FastTouchesDontGetStuck()
    {
        var device = InputSystem.AddDevice<Touchscreen>();

        InputSystem.QueueStateEvent(device,
            new TouchState
            {
                phase = PointerPhase.Began,
                touchId = 0,
            });

        InputSystem.QueueStateEvent(device,
            new TouchState
            {
                phase = PointerPhase.Ended,
                touchId = 0,
            });

        InputSystem.QueueStateEvent(device,
            new TouchState
            {
                phase = PointerPhase.Began,
                touchId = 0,
            });

        InputSystem.QueueStateEvent(device,
            new TouchState
            {
                phase = PointerPhase.Ended,
                touchId = 0,
            });
        InputSystem.Update();
        InputSystem.Update();

        Assert.That(device.activeTouches.Count, Is.EqualTo(0));
        Assert.That(device.allTouchControls[0].phase.ReadValue(), Is.EqualTo(PointerPhase.None));
    }
`

**Comment by jackpr-unity** [comment] 2019-02-08 22:24
Still present with 2018.3.5f1 and commit 5d0704c

**Comment by JiaUnity** [comment] 2019-03-06 00:05
It seems the multiple-touch handling is fixed long time ago. Closing.

**Closed as completed by JiaUnity** 2019-03-06 00:05 UTC
Labels: bug
