### ISSUE TITLE
Default path for generated .cs files creates additional "Assets" folder

### ISSUE THREAD

**Issue by TomasRiker** [Unity-Technologies/InputSystem#731] opened 2019-07-19 07:07 UTC
If you tick an InputAction asset's "Generate C# Class" option in the Inspector and don't change the "C# Class File" path, you will end up with another "Assets" folder inside your already existing "Assets" folder.

**Comment by SKroell** [comment] 2019-07-19 07:33
Duplicate of #653 & #535

Issue already seems to be fix on both current stable and develop branch.

**Comment by Rene-Damm** [comment] 2019-07-19 21:18
0.9-preview is out now. Has the fix.

**Closed as completed by Rene-Damm** 2019-07-19 21:18 UTC
