### ISSUE TITLE
[Gamepad] Press Modifier used from Input Action Set only works if I mash the button

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#84] opened 2018-04-26 06:35 UTC
Commit 7948ead, Win10 64, 2018.2b1
XBOX One Controller, XBOX 360 Controller (both USB).

Repro 3/3

A face button with a PressModifier only seems to generate events when I mash the button rapidly. I tested buttonNorth and buttonSouth.

**Comment by Rene-Damm** [comment] 2018-04-26 17:57
I think this is fixed by a native change that is making its way into the beta. I'll keep this open until it's hit the beta and has been verified.

The problem is that in the current setup, native pumps input events invariably in both player and editor updates and then sorts it out on the managed side which state to route the updates into. This can mean that input updates meant for the player are processed in the editor update. Especially, with actions that has started leading to problems and the button press logic is broken due to it.

The reason that mashing helped is because it increased the likelihood that eventually some input would end up in the player update and not in the editor update (which tends to grab the lion share of input).

With the native change in place, native will now decide which updates to route input into -- either the player or the editor.

**Comment by Rene-Damm** [comment] 2018-06-08 22:42
Should be fixed in latest beta. Please let us know if you still see the issue.

**Closed as completed by Rene-Damm** 2018-06-08 22:42 UTC
Labels: bug

**Comment by periodyctom** [comment] 2018-06-08 23:04
I'll try and check this weekend or next week, depending on my schedule.

**Comment by periodyctom** [comment] 2018-06-17 01:14
This seems resolved now.

**Comment by Rene-Damm** [comment] 2018-06-18 19:01
Thank you for checking :)
