### ISSUE TITLE
Release-Only Button Interaction Produces no events

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#492] opened 2019-03-24 21:03 UTC
[PressButtonGamepadMinRepro.zip](https://github.com/Unity-Technologies/InputSystem/files/3000846/PressButtonGamepadMinRepro.zip)

This updated sample shows that buttonNorth/keyboard a produce no events when the action is set to "Release" and not "Press" or "PressAndRelease".

Win10 64, tested with keyboard, PS4 DualShock, and XBOX One Gamepads. 0.2.6-preview

**Comment by Rene-Damm** [comment] 2019-04-08 16:18
Confirmed. Looking into it. Thank you for the excellent repro.

**Comment by Rene-Damm** [comment] 2019-04-09 12:35
Should be fixed in https://github.com/Unity-Technologies/InputSystem/pull/526.

Problem occurred only when there were multiple controls bound to the same action. The disambiguation code didn't work correctly when a control was actuated but the actuation was ignored by an interaction (in this case `PressInteraction` ignoring it because it would trigger only on release). When the actuation of the control went away (button released), the disambiguation code then just silently swallowed the state change.

**Closed as completed by Rene-Damm** 2019-04-09 12:35 UTC
Labels: bug
