### ISSUE TITLE
[Win] Touch.radius always 0

### ISSUE THREAD

**Issue by feipinxiang** [Unity-Technologies/InputSystem#388] opened 2019-01-23 14:02 UTC
In the unity editor, Touch.radius is always equal to 0.But the c# wpf project I created can get System.Windows.Input.TouchPoint.size.

Debug.Log(Input.touches[0].radius);
Debug.Log(Input.touches[0].radiusVariance);
or
Debug.Log(Input.GetTouch(0).radius);
Debug.Log(Input.GetTouch(0).radiusVariance);

Unity 2018.2.2f1 (64-bit)/Unity 2017.4.10f1 (64-bit)
system windows 10 x64. dell xps 15 touch screen.

Input.multiTouchEnabled:True
Input.simulateMouseWithTouches:True
Input.stylusTouchSupported:False
Input.touchPressureSupported:False
Input.touchSupported:True

**Comment by feipinxiang** [comment] 2019-01-23 14:05
wpf code:

> Touch.FrameReported += new TouchFrameEventHandler(Touch_FrameReported);
void Touch_FrameReported(object sender, TouchFrameEventArgs e)
{
	foreach (TouchPoint _touchPoint in e.GetTouchPoints(this.canvas1))
	{
	    Console.WriteLine(_touchPoint.Size.ToString());
	}
}

**Comment by Rene-Damm** [comment] 2019-01-23 18:46
Not sure whether the problem is on our side or on the side of the API we're using to get the data. We do read out contact area information from TOUCHINPUT, if available. Needs checking.

**Comment by douglas-piconi** [comment] 2019-01-25 21:37
@feipinxiang   this bug is with the legacy input manager in Unity.   We have the bug filed with your sample project in the other bug system.  I am going to close this bug in GitHub as this project is a different input system.

the public link to the bug is https://issuetracker.unity3d.com/issues/touch-dot-radius-is-always-0-when-using-windows-touch-screen

**Closed as completed by douglas-piconi** 2019-01-25 21:37 UTC
Labels: bug
