### ISSUE TITLE
Cannot rename control scheme in Input Actions asset editor

### ISSUE THREAD

**Issue by YLlywelyn** [Unity-Technologies/InputSystem#554] opened 2019-04-18 01:37 UTC
When editing an InputActions asset, whatever I type as the name for a new control scheme, it always has the name "New control scheme".  This happens when creating a new control scheme or editing an existing one.  Expected behaviour would be for the control scheme to be named what I named it (eg. "XInput" or "Keyboard").

**Comment by JiaUnity** [comment] 2019-04-20 00:16
Not the case for me.
![RenameAction](https://user-images.githubusercontent.com/33637761/56448735-b9194b00-62c6-11e9-8259-aa3d72be861e.gif)
@JMSams What's the ISX package version and Unity version?

**Comment by YLlywelyn** [comment] 2019-04-20 08:20
I can rename actions fine, it's when I try to name my control schemes I have issues.

Unity 2019.1.0f
Input system 0.2.6

**Comment by Rene-Damm** [comment] 2019-04-23 13:05
This is a bug that has since been fixed on the `develop` branch. The problem is with focus. The renaming actually works but ONLY if you hit enter :) We were using a text field that only resulted in a change when you pressed enter OR focus moved away from the text field. For some reason I never quite pinpointed, the latter never worked. So you HAD to press enter or nothing happened.

On latest `develop` we switched away from this kind of text field. Should work as expected.

Fix should be in next package (due out this week).

**Closed as completed** 2019-04-23 13:06 UTC
Labels: bug

**Comment by YLlywelyn** [comment] 2019-04-23 13:21
kl, thanks :)
