### ISSUE TITLE
[Linux] Mouse position is wrong

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#363] opened 2019-01-02 20:52 UTC
https://forum.unity.com/threads/testing-a-simple-mouse-position-using-the-new-input-system.605164/

**Comment by JeromyStroh** [comment] 2019-02-15 19:49
Dupe of https://issuetracker.unity3d.com/issues/linux-mouse-editor-mouse-position-is-inconsistent-with-the-old-input

Has been fixed internally.

**Closed as completed** 2019-02-21 14:32 UTC
Labels: bug
