### ISSUE TITLE
0.9.6 - PlayerInput component invoke unity events doesn't show events anymore.

### ISSUE THREAD

**Issue by JamhammerRob** [Unity-Technologies/InputSystem#851] opened 2019-09-09 21:36 UTC
No action maps appear when you switch the event type to invoke unity events.

**Comment by interior-night** [comment] 2019-09-10 12:45
Same for me. The issue is here:

```ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
UnityEngine.InputSystem.Editor.PlayerInputEditor.OnActionAssetChange () (at Library/PackageCache/com.unity.inputsystem@0.9.6-preview/InputSystem/Plugins/PlayerInput/PlayerInputEditor.cs:442)
UnityEngine.InputSystem.Editor.PlayerInputEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.inputsystem@0.9.6-preview/InputSystem/Plugins/PlayerInput/PlayerInputEditor.cs:61)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass53_0.<CreateIMGUIInspectorFromEditor>b__0 () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:502)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by lernhart** [comment] 2019-09-14 23:07
Until a fix comes up, reverting back to 0.9.5 works. I guess, the issue was introduced in 0.9.6

**Comment by interior-night** [comment] 2019-09-15 03:04
No one assigned to this bug yet? PlayerInput is one of the main components of the new system and yet is broken. Seems like a "high priority" issue to me.

**Comment by jakkos-net** [comment] 2019-09-16 10:32
I was pulling my hair out thinking I was reading the docs wrong and forgetting to do something.

> Until a fix comes up, reverting back to 0.9.5 works. I guess, the issue was introduced in 0.9.6

This worked immediately for me, thanks!

**Comment by pmurph0305** [comment] 2019-10-14 18:57
Still not working in the current preview package that was just written about in a blog post today.
Additionally in the Simple Demo, Action methods listed as Missing are still called correctly.

Package Version: 1.0.0
Unity Version: 2019.2.7f2
Quick Reproduction Steps:
1. Create a new project and import Input System
2. Import "Simple Demo" into project after importing Input System
3. Load Scene "SimpleDemo_UsingPlayerInput.unity"
4. Select "Player" Gameobject
5. Expand Events-> gameplay on Player Input (script) component.

Current Behaviour:
Action methods are listed as Missing, and are unselectable from the "SimpleController_UsingPlayerInput.cs" script but still function correctly in the scene.

Expected:
Available action methods should be selectable from the Player Input Script.
Events listed as Missing should not be called.

**Comment by Rene-Damm** [comment] 2019-10-14 20:04
>Action methods are listed as Missing, and are unselectable from the "SimpleController_UsingPlayerInput.cs" script but still function correctly in the scene.

This is a regression that was introduced in Unity itself with respect to UnityEvents. It's been fixed in the latest 2019.3 beta and a backport tp 2019.2 (2019.1 doesn't have the regression) is on the way as far as I remember. I'll check tomorrow.

**Comment by scott-lin** [comment] 2019-10-21 03:31
@Rene-Damm, what'd you find out? Any ETA on the backport? Thanks.

**Comment by Rene-Damm** [comment] 2019-10-24 16:13
2019.2.10f1 has the fix.

**Closed as completed by Rene-Damm** 2019-10-24 16:13 UTC
Labels: bug
