### ISSUE TITLE
Input processing is broken when starting new project / after installing package

### ISSUE THREAD

**Issue by plunntic** [Unity-Technologies/InputSystem#672] opened 2019-06-10 21:18 UTC
It seems to be broken when starting new project: after going to package manager and installing input system package it displays a message about native input backends required and asks to enable those (and also, that Unity restart will be required).

But Unity doesn't restart after clicking `yes` and input processing is broken: i can see input beeing fired in the input debugger console, but it doesn't fire events.

Restarting Unity manually does not help as far as i can tell, for the time being im just rebooting the whole system. After reboot it seems to work fine.

**Comment by JiaUnity** [comment] 2019-06-14 23:10
Hey. Could you tell us the system you use and the Unity Editor version?
Thanks!

**Comment by plunntic** [comment] 2019-06-15 05:06
Hi, it was on Windows 10, using Unity 2019.1.6f1 (f2970305fe1c) and input system 0.2.10-preview

**Comment by JiaUnity** [comment] 2019-06-20 02:38
> But Unity doesn't restart after clicking yes and input processing is broken: i can see input beeing fired in the input debugger console, but it doesn't fire events.

Did you also copy/paste project in from somewhere else?

**Comment by orlax** [comment] 2019-06-24 21:43
hey there, i can fonfirm this is happening to me as well, installed the package and received the same alert window about the backends, but in my case even after restarting the system input is not registered. 

i followed [this brackeys video](https://www.youtube.com/watch?v=Pzd8NhcRzVo) to implement input recognition but even thought i can see the input being recived on the input debug window events are not fired. 

my unity  version is: 2019.1.1f1 
package version: 0.2.8
windows 10  Home N with up to date updates. 

i am going back to the regular input system for the moment. but thought would be good to share.

**Comment by orlax** [comment] 2019-06-24 21:46
this is my own project using the unity collaborate feature, no copy/paste from anywhere.

**Comment by plunntic** [comment] 2019-06-24 22:58
> Did you also copy/paste project in from somewhere else?

No, i've been trying out new features / packages, thus making a lot of new empty projects. The problem with Unity not restarting and events not being fired appeared only after a few of them. First four or five i think projects went fine, and then it sopped working - meaning it stopped restarting the Unity after input system installation and making me restart the whole computer every time i start a new project and install input system package.

**Comment by JiaUnity** [comment] 2019-07-01 23:49
@plunntic 
>Unity doesn't restart after clicking yes and input processing is broken: i can see input beeing fired in the input debugger console, but it doesn't fire events.

This is by design. If you read the dialog popup from importing the package, it doesn't say it would restart the Editor.
![PackageChange](https://user-images.githubusercontent.com/33637761/60472425-ab186c80-9c1d-11e9-9586-42ab8cf7b0b6.jpg)

> it stopped restarting the Unity after input system installation and making me restart the whole computer every time i start a new project and install input system package.
I have many questions about this:

1. > it stopped restarting the Unity after input system installation

As I said above, importing ISX package doesn't restart the Editor automatically, but if you go to Project Settings and change the Active Input Handling, the Editor does restart and this process has no issue. Is this how you restart the Editor for the first few times?

2. > making me restart the whole computer every time i start a new project and install input system package

Did the Editor or Windows ask you to do this, or just something you did to get around the issue? 

3. I still cannot repro this issue, and seems you are switching projects around, so I need some specifics about this.
Before you restart the computer, does the ISX stop working for all projects, or just the one just created?
After you restart the computer, did you create a new one, or open the old one from before restarting? 

If you can upload a project you made, it may help us to identify the issue sooner. Thanks!

**Comment by JiaUnity** [comment] 2019-07-02 00:01
@orlax 
> i followed this brackeys video to implement input recognition

Have you had ISX working successfully with the project, or it only happens when you import new package?

> i can see the input being recived on the input debug window events are not fired.

I take you can see the Action list, right? Unfortunately, the list can only tell if the Input Action is in effect and has a list of all its bindings. It does not tell you if the action is triggered or not. 
I suspect there are other factors that stop the ISX from working. If you can upload a sample project, I may be able to figure out what the issue is. 
Thanks.

**Comment by orlax** [comment] 2019-07-02 15:44
@JiaUnity hello! 

this is the first time I try to use the ISX i haven't used it before. 

not only the action list,  on the input debug window where unity logs all the inputs received by the editor i can see the inputs on my controllers being recognized but nothing fires on the ISX, i have made sure to follow available documentation (and the brackeys video) but was not able to make it work. 

I will try again today and upload a sample project so you can check it out if you can. Thank you a lot for your help.

**Comment by Rene-Damm** [comment] 2019-11-18 14:16
Forcing a restart automatically from the install path is on the request list.

Closing this issue as part of our migration to FogBugz.

**Closed as completed by Rene-Damm** 2019-11-18 14:16 UTC
Labels: bug
