### ISSUE TITLE
ArgumentOutOfRangeException when removing callback when invoked

### ISSUE THREAD

**Issue by matanshukry** [Unity-Technologies/InputSystem#942] opened 2019-11-01 23:48 UTC
My setup is a bit complex, but the issue is that when we register a method callback to the performed property, and in that method execution removing the callback, an exception is throw.

How to reproduce:
(1) Get an action somehow (Reference would be easiest, I'm assuming)
(2) Add a callback to it: `mAction.performed += OnPerformed`
(3) In the method execution, remove the callback:
```
        private void OnPerformed(InputAction.CallbackContext obj)
        {
            mAction.performed -= OnPerformed;
        }
```

That will create 2 exceptions in the log:
```
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
UnityEngine.InputSystem.Utilities.InlinedArray`1[TValue].get_Item (System.Int32 index) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.1/InputSystem/Utilities/InlinedArray.cs:66)
UnityEngine.InputSystem.InputActionState.CallActionListeners (System.Int32 actionIndex, UnityEngine.InputSystem.InputActionMap actionMap, UnityEngine.InputSystem.InputActionPhase phase, UnityEngine.InputSystem.Utilities.InlinedArray`1[System.Action`1[UnityEngine.InputSystem.InputAction+CallbackContext]]& listeners) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.1/InputSystem/Actions/InputActionState.cs:1613)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)
```

and, which seems more accurate:
```
ArgumentOutOfRangeException thrown during execution of 'Performed' callback on action 'UI/Cancel[/Keyboard/escape,/Mouse/backButton]'
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)
```

**Comment by m4ff** [comment] 2019-12-16 16:08
I'm also getting the same error. In my case the root cause is even more hidden: a callback is disabling another MonoBehaviour that is clearing its callbacks on the same input action.

Looking at the source code (1.0.0-preview.3) it is clear that the problem is the `listeners` array being modified by the callbacks.

```
var listenerCount = listeners.length;
for (var i = 0; i < listenerCount; ++i)
{
    try
    {
        listeners[i](context);
    }
    catch (Exception exception)
    {
        Debug.LogError(
            $"{exception.GetType().Name} thrown during execution of '{phase}' callback on action '{GetActionOrNull(ref actionStates[actionIndex])}'");
        Debug.LogException(exception);
    }
}
```

**Comment by orororo** [comment] 2020-02-18 00:23
Same. No error if I just wait for the next frame to remove the callback.

**Comment by Rene-Damm** [comment] 2020-02-18 09:16
@orororo Which version of the package are you using? I'd expect this problem to be fixed as of latest.

**Comment by orororo** [comment] 2020-02-18 09:41
I was using preview 4. I just updated to 5 and it seems ok (I wasn't expecting an update so soon ^^)
Good work !

**Comment by Rene-Damm** [comment] 2020-02-18 10:44
Thank you for confirming!

**Closed as completed by Rene-Damm** 2020-02-18 10:44 UTC
